[versions]
kotlin = "2.3.20"
agp = "9.1.0"
kotlinxCoroutines = "1.10.2"

[plugins]
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-kotlin-multiplatform = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }